[package]
name = "gcui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4"
anyhow = "1.0.54"
serde = { version = "1", features = ["derive"] }
csv = "^1.1.6"
clap = "3.1.0"
